# Generated by Django 5.2 on 2025-04-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enrolled_programs',
            field=models.ManyToManyField(blank=True, to='health.healthprogram'),
        ),
    ]
